efir/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("pridat/<int:product_id>", views.cart_add, name="cart_add"),
    path("odebrat/<int:product_id>", views.cart_remove, name="cart_remove"),
    path("clean_cart_session", views.clean_cart_session, name="clean_cart_session"),
    path(
        "update_cart_quantity/<str:item_id>",
        views.update_cart_quantity,
        name="update_cart_quantity",
    ),
    path("detail", views.cart_detail, name="cart_detail"),
    path("update_cart_country/", views.update_cart_country, name="update_cart_country"),
]

efir/coupons/urls.py
from django.urls import path

from . import views

app_name = "coupons"

urlpatterns = [
    path("apply", views.coupon_apply, name="apply"),
    path("deactivate", views.coupon_deactivate, name="coupon_deactivate"),
    path("delete", views.coupon_delete, name="delete"),
    path("create_coupon/", views.coupon_create, name="create_coupon"),
    path("generate_vouchers", views.generate_vouchers, name="generate_vouchers"),
    path("repair_vouchers", views.repair_vouchers, name="repair_vouchers"),

    # Add other URL patterns as needed
]

efir/orders/urls.py
from django.urls import path

from . import views
from .views import *

app_name = "orders"


urlpatterns = [
    path("invoice", views.invoice, name="invoice"),
    path("contact_form", views.contact_form, name="contact_form"),
    path(
        "media/assets/<str:file_name>",
        views.download_ppl_label,
        name="download_ppl_label",
    ),
    path("new", views.new_order, name="new_order"),
    path(
        "send_offer_confirmation/<int:order_id>/",
        views.send_offer_confirmation,
        name="send_offer_confirmation",
    ),
    path(
        "send_paid_offer_confirmation/<int:order_id>/",
        views.send_paid_offer_confirmation,
        name="send_paid_offer_confirmation",
    ),
    path("update_orders", views.update_orders, name="update_orders"),
    path("cleanup_orders", views.cleanup_orders, name="cleanup_orders"),
]

efir/orders/models.py
from decimal import Decimal

from django.conf import settings
from django.db import models
from django.utils import timezone

from catalog.models import Product


class Order(models.Model):
    etb_id = models.CharField(max_length=50, verbose_name="Efir ID")
    first_name = models.CharField(max_length=50, verbose_name="Jméno")
    last_name = models.CharField(max_length=50, verbose_name="Příjmení")
    birthday = models.DateField(verbose_name="Datum narození", null=True, blank=True)
    email = models.CharField(max_length=50, verbose_name="Email")
    number = models.CharField(max_length=20, verbose_name="Telefonní číslo")
    comments = models.TextField(blank=True, verbose_name="Komentáře")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno")
    updated = models.DateTimeField(auto_now=True, verbose_name="Aktualizováno")

    COUNTRY_CHOICES = [("CZ", "cz"), ("SK", "sk")]

    country = models.CharField(max_length=20, verbose_name="Země")
    shipping_type = (  # TODO I need to add new option personal pickup here
        ("", "Vyberte si způsob dopravy"),
        ("P", "PPL"),
        ("D", "PPL - Doručení domů"),
        ("Z", "Zásilkovna"),
        ("O", "Online"),
        ("S", "Osobní odběr"),
    )
    shipping = models.CharField(
        max_length=100,
        choices=shipping_type,
        verbose_name="Doprava",
        default="Zásilkovna",
    )
    shipping_price = models.DecimalField(
        decimal_places=0,
        max_digits=4,
        blank=True,
        default=Decimal("0"),
        verbose_name="Cena dopravy (CZK)",
    )
    address = models.CharField(max_length=250, verbose_name="Adresa", blank=False)
    city = models.CharField(max_length=250, verbose_name="City", blank=True, null=True)
    zipcode = models.CharField(
        max_length=250, verbose_name="Zipcode", blank=True, null=True
    )

    vendor_id = models.CharField(
        max_length=250,
        verbose_name="ID prodejce",
        blank=False,
    )
    discount = models.DecimalField(
        decimal_places=0,
        max_digits=10,
        blank=True,
        default=Decimal("0"),
        verbose_name="Sleva (CZK)",
    )
    total_cost = models.DecimalField(
        decimal_places=2,
        max_digits=10,
        blank=True,
        default=Decimal("0.00"),
        verbose_name="Celková cena (CZK)",
    )

    stripe_id = models.CharField(max_length=250, blank=True, verbose_name="Stripe ID")
    zasilkovna_id = models.CharField(
        max_length=250, blank=True, verbose_name="Zásilkovna ID"
    )
    paid = models.BooleanField(default=False, verbose_name="Zaplaceno")
    shipped = models.BooleanField(default=False, verbose_name="Vyřízeno")
    newsletter_consent = models.BooleanField(
        default=False, verbose_name="Souhlas - newsletter", null=True, blank=True
    )
    author_comment = models.CharField(
        max_length=200, blank=True, verbose_name="ETB poznamka k objednavce"
    )
    discount_code = models.CharField(
        max_length=15, blank=True, default="-", verbose_name="Slevovy kod"
    )
    coupon_id = models.CharField(
        max_length=15, blank=True, default="-", verbose_name="ID certifikatu"
    )
    label = models.CharField(
        max_length=200, blank=True, null=True, verbose_name="Etiketa k doprave"
    )  # Or use FilePathField if you want to restrict to a certain directory

    confirmation_sent = models.BooleanField(
        default=False, verbose_name="Emailove potvrzení objednávky"
    )
    shipped_sent = models.BooleanField(
        default=False, verbose_name="Email předáno k dopravci"
    )

    class Meta:
        verbose_name = "Objednávky"
        verbose_name_plural = "Objednávky"
        ordering = ["-created"]
        indexes = [
            models.Index(fields=["-created"]),
        ]

    def __str__(self):
        return f"Objednávka {self.id}"

    def get_stripe_url(self):
        if not self.stripe_id:
            return ""
        elif "_test_" in settings.STRIPE_SECRET_KEY:
            path = "/test/"
        else:
            path = "/"

        return f"https://dashboard.stripe.com{path}payments/{self.stripe_id}"

    def get_zasilkovna_url(self):
        pass

    def save(self, *args, **kwargs):
        # self.shipping_price = self.calculate_shipping_price()

        if "cart" in kwargs:
            cart = kwargs.pop("cart")
            cart.get_total_price_after_discount()

            self.shipping_price = cart.get_shipping_price()
            self.discount = cart.transfer_discount_to_orders()
            self.total_cost = cart.get_total_price_after_discount()

        if not self.etb_id:
            today_date = timezone.now().strftime("%y%m%d")
            today_order_count = Order.objects.filter(
                created__date=timezone.now().date()
            ).count()
            self.etb_id = f"{today_date}{today_order_count:02d}"

        """ vendor_id = kwargs.pop("vendor_id", None)
        if vendor_id:
            self.vendor_id = vendor_id

        print(f"model order printing vendor_id{vendor_id}")"""

        super().save(*args, **kwargs)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name="order_items", on_delete=models.CASCADE
    )
    price = models.DecimalField(
        decimal_places=0, max_digits=10, verbose_name="Cena za kus (CZK)"
    )
    total_price = models.DecimalField(
        decimal_places=0,
        max_digits=10,
        verbose_name="Cena (CZK)",
        default=0,
    )
    surcharge = models.DecimalField(
        decimal_places=0,
        max_digits=10,
        verbose_name="Příplatek za šití na míru (CZK)",
        default=0,
    )
    quantity = models.PositiveIntegerField(default=1, verbose_name="Množství")

    zpusob_vyroby = models.CharField(max_length=50)
    velikost = models.CharField(
        max_length=50, null=True, blank=True, verbose_name="Individuální velikost"
    )
    kalhotky_velikost_set = models.CharField(max_length=50, null=True, blank=True)
    podprsenka_velikost_set = models.CharField(max_length=50, null=True, blank=True)
    pas_velikost_set = models.CharField(max_length=50, null=True, blank=True)

    poznamka = models.TextField(blank=True)
    slevovy_kod = models.CharField(
        max_length=20, default="-", verbose_name="Slevový kód"
    )
    hodnota_kuponu = models.CharField(
        max_length=20, default="-", verbose_name="Hodnota kuponu"
    )
    certificate_from = models.CharField(
        max_length=100, default="-", verbose_name="Od koho"
    )
    certificate_to = models.CharField(max_length=100, default="-", verbose_name="Komu")

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

efir/cart/forms.py
from django import forms
from django.shortcuts import get_object_or_404

from catalog.models import Product, ProductSet

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
"""ZPUSOB_VYROBY_CHOICES = [
    ("Skladem", "Skladem"),
    ("Na_Miru", "Na Míru"),
]"""
"""OBVOD_PRSA_CHOICES = [(obj.id, str(obj)) for obj in ObvodHrudnik.objects.all()]
OBVOD_HRUDNIK_CHOICES = [(obj.id, str(obj)) for obj in ObvodPrsa.objects.all()]

OBVOD_PRSA_CHOICES = [
    (str(i) + j, str(i) + j) for i in range(70, 111, 5) for j in ["A", "B", "C"]
]
OBVOD_PRSA_CHOICES.append((0, "-"))
OBVOD_HRUDNIK_CHOICES = [(i, str(i)) for i in ["XS", "S", "M", "L"]]
OBVOD_HRUDNIK_CHOICES.append((0, "-"))
OBVOD_BOKY_CHOICES = [(i, str(i)) for i in ["XS", "S", "M", "L"]]
OBVOD_BOKY_CHOICES.append((0, "-"))"""


class CartAddProductForm(forms.Form):
    def __init__(self, id_from_product, *args, **kwargs):
        super(CartAddProductForm, self).__init__(*args, **kwargs)
        product_id = id_from_product

        product = get_object_or_404(Product, id=product_id)

        try:
            productset = ProductSet.objects.get(product_id=product_id)

            kalhotky_available_sizes = []
            kalhotky_velikost = productset.get_kalhotky_sizes()
            for kalhotky_size in kalhotky_velikost:
                kalhotky_available_sizes.append(kalhotky_size)
            kalhotky_available_sizes = tuple(kalhotky_available_sizes)
            kalhotky_available_sizes = [(i, i) for i in kalhotky_available_sizes]

            podprsenka_available_sizes = []
            podprsenka_velikost = productset.get_podprsenky_sizes()
            for podprsenka_size in podprsenka_velikost:
                podprsenka_available_sizes.append(podprsenka_size)
            podprsenka_available_sizes = tuple(podprsenka_available_sizes)
            podprsenka_available_sizes = [(i, i) for i in podprsenka_available_sizes]

            pas_available_sizes = []
            pas_velikost = productset.get_pas_sizes()
            for pas in pas_velikost:
                pas_available_sizes.append(pas)
            pas_available_sizes = tuple(pas_available_sizes)
            pas_available_sizes = [(i, i) for i in pas_available_sizes]

        except ProductSet.DoesNotExist:
            # Handle the case where the product set doesn't exist
            productset = None
            kalhotky_available_sizes = []
            podprsenka_available_sizes = []
            pas_available_sizes = []

        available_sizes = []
        velikost = product.get_available_sizes()  # list
        for one_size in velikost:
            available_sizes.append(one_size)
        available_sizes = tuple(sorted(available_sizes))
        available_sizes = [(i, i) for i in available_sizes]

        """obvod_hrudnik = tuple(product.obvod_hrudnik.values_list())
        obvod_hrudnik_list = []
        for item in obvod_hrudnik:
            obvod_hrudnik_list.append(item)
        obvod_hrudnik_list.append((0, "-"))
        obvod_hrudnik_list = sorted(obvod_hrudnik_list)
        """
        """ obvod_hrudnik = tuple(product.obvod_hrudnik.values_list())
        obvod_hrudnik_list = [(i[1], str(i[1])) for i in obvod_hrudnik]
        obvod_hrudnik_list.append(("-", "-"))

        obvod_prsa = tuple(product.obvod_prsa.values_list())
        obvod_prsa_list = [(i[1], str(i[1])) for i in obvod_prsa]
        obvod_prsa_list.append(("-", "-"))

        def extract_numeric_part(value):
            match = re.search(r"\d+", value)
            if match:
                return int(match.group())
            else:
                return float("inf")

        # https://www.regular-expressions.info/refcapture.html
        def extract_letter_part(value):
            match = re.search(r"[A-Za-z]+", value)
            if match:
                return match.group()
            else:
                return ""

        obvod_prsa_list = sorted(
            obvod_prsa_list,
            key=lambda x: (extract_numeric_part(x[1]), extract_letter_part(x[1]))
            if x[1] != "-"
            else (float("inf"), ""),
        )

        obvod_boky = tuple(product.obvod_boky.values_list())
        obvod_boky_list = [(i[1], str(i[1])) for i in obvod_boky]
        obvod_boky_list.append(("-", "-"))

        obvod_body = tuple(product.obvod_body.values_list())
        obvod_body_list = [(i[1], str(i[1])) for i in obvod_body]
        obvod_body_list.append(("-", "-"))

        obvod_body_list = sorted(
            obvod_body_list, key=lambda x: int(x[1]) if x[1] != "-" else float("inf")
        )"""

        zpusob_vyroby = tuple(product.zpusob_vyroby.values_list())
        zpusob_vyroby_list = [(i[1], str(i[1])) for i in zpusob_vyroby]

        self.fields["quantity"] = forms.TypedChoiceField(
            label="Quantity",
            choices=PRODUCT_QUANTITY_CHOICES,
            coerce=int,
            initial=0,
            widget=forms.Select(attrs={"id": "id_quantity"}),
        )
        self.fields["velikost"] = forms.TypedChoiceField(
            label="Velikost",
            choices=available_sizes,
            initial="-",
            required=False,
        )

        self.fields["zpusob_vyroby"] = forms.TypedChoiceField(
            label="Způsob výroby",
            choices=zpusob_vyroby_list,
            initial="Kofekční velikost",
            required=False,
        )
        self.fields["override"] = forms.BooleanField(
            required=False, initial=False, widget=forms.HiddenInput
        )
        self.fields["poznamka"] = forms.CharField(
            label="Poznamka",
            max_length=1600,
            widget=forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Obvod hrudníku:\nObvod pod hrudníkem:\nObvod jednoho prsa:\nObvod pasu:\nObvod boků:",
                }
            ),
            required=True,
            help_text="Vyplňte tyto hodnoty: Obvod hrudníku Obvod pod hrudníkem Obvod jednoho prsa Obvod pasu Obvod boku",
        )

        self.fields["kalhotky_velikost_set"] = forms.TypedChoiceField(
            label="Velikost kalhotek v setu",
            choices=kalhotky_available_sizes,
            required=False,
        )

        self.fields["podprsenka_velikost_set"] = forms.TypedChoiceField(
            label="Velikost podprsenky v setu",
            choices=podprsenka_available_sizes,
            required=False,
        )

        self.fields["pas_velikost_set"] = forms.TypedChoiceField(
            label="Velikost pasu v setu",
            choices=pas_available_sizes,
            required=False,
        )

        self.fields["certificate_from"] = forms.CharField(
            label="certificate_from",
            widget=forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Od koho je tento certifikát?",
                }
            ),
            required=True,
            help_text="Od koho je tento certifikát?",
        )

        self.fields["certificate_to"] = forms.CharField(
            label="certificate_to",
            widget=forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Pro koho je tento certifikát?",
                }
            ),
            required=True,
            help_text="Pro koho je tento certifikát?",
        )

    def set_cart_values(self):
        zpusob_vyroby_value = self.cleaned_data.get("zpusob_vyroby", None)

        if zpusob_vyroby_value == "Skladem":
            self.cleaned_data["poznamka"] = "\u200B"
            self.cleaned_data["certificate_from"] = "\u200B"
            self.cleaned_data["certificate_to"] = "\u200B"

        elif zpusob_vyroby_value == "Na Míru":
            self.cleaned_data["velikost"] = "\u200B"
            self.cleaned_data["kalhotky_velikost_set"] = "\u200B"
            self.cleaned_data["podprsenka_velikost_set"] = "\u200B"
            self.cleaned_data["pas_velikost_set"] = "\u200B"
            self.cleaned_data["certificate_from"] = "\u200B"
            self.cleaned_data["certificate_to"] = "\u200B"
        elif zpusob_vyroby_value == "Tištěný":
            self.cleaned_data["velikost"] = "\u200B"
            self.cleaned_data["poznamka"] = "\u200B"
            self.cleaned_data["kalhotky_velikost_set"] = "\u200B"
            self.cleaned_data["podprsenka_velikost_set"] = "\u200B"
            self.cleaned_data["pas_velikost_set"] = "\u200B"
        else:
            self.cleaned_data["velikost"] = "\u200B"
            self.cleaned_data["poznamka"] = "\u200B"
            self.cleaned_data["kalhotky_velikost_set"] = "\u200B"
            self.cleaned_data["podprsenka_velikost_set"] = "\u200B"
            self.cleaned_data["pas_velikost_set"] = "\u200B"

        # this happens when saved to cart
        return zpusob_vyroby_value

efir/cart/templates/cart/cart_backups/cart_new.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load i18n %}
{% load humanize %}

{% block content %}
<style>
   #id_quantity, #id_obvod_hrudnik, #id_obvod_prsa {
   appearance: none;
   -webkit-appearance: none;
   -moz-appearance: none;
   background-color: transparent;
   font-size: 0.8rem;
   width: 30px; /* Adjust the width as needed */
   text-align: center;
   border: 1px solid black; /* Add black square border */
   }

   body {
      font-size: 0.8rem;
   }      
   
</style>

<div class="container px-4 py-5 mx-auto mb-5" style="max-width: 800px; min-height: 400px;">
   <div class="row d-flex justify-content-center">
      <h4 class="heading">Objednávka</h4>
   </div>
   {% if cart|length > 0 %}
   <div class="row d-flex py-2 justify-content-center border-top">
      {% for item in cart %}
      {% with product=item.product %}

      <div class="my-auto py-3 col-4">
         <div class="row d-flex">
            <div class="book">
               <img src="{{ product.image1.url }}" class="book-img" style="max-height: 200px; max-width: 100%;">
            </div>
         </div>
      </div>
      <div class="my-auto py-3 col-8">
         <div class="row text-right">
            <div class="col-6">
               <h6 class="mob-text">{{ product.name }}</h6>
            </div>
            <div class="col-6">
               <!-- Cart Remove Function--> 
               <div style="text-align: left;">
                  <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                     {% csrf_token %}
                     <button type="submit" class="btn-close" aria-label="Close">
                        Close
                     </button>
                  </form>
               </div>
            </div>
         </div>
         <form id="update-quantity-form" action="{% url 'cart:cart_add' item.product.id %}" method="post">
            {% csrf_token %}
            <div class="mob-text">
               <div class="row">
                  <div class="col-6">
                     <p>{{ item.update_quantity_form.zpusob_vyroby }}</p>
                  </div>
                  <div class="col-6">
                     
                  </div>
               </div>
               <div class="row">
                  <div class="col-6">
                     <p class="mob-text" id="obvod_prsa">Obvod prsa:</p>
                  </div>
                  <div class="col-6">
                     {{ item.update_quantity_form.obvod_prsa }}
                  </div>
               </div>
               <div class="row">
                  <div class="col-6">
                     <p class="mob-text" id="obvod_hrudnik">Obvod hrudníku:</p>
                  </div>
                  <div class="col-6">
                     {{ item.update_quantity_form.obvod_hrudnik }}
                  </div>
               </div>
            </div>
            <div class="row text-right">
               <div id="update-quantity-code mb-0" class="col-6">
                  <div class="d-flex">
                     <div class="input-group">
                        <button class="btn btn-outline-dark rounded-0" name="update-quantity-form" type="button" onclick="decreaseCount()" style="width: 30px; height: 30px; display: flex; align-items: center; justify-content: center;">
                           <i class="bi bi-dash" style="line-height: 1;"></i>
                        </button>
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.override }}
                        <button class="btn btn-outline-dark rounded-0" name="update-quantity-form" type="button" onclick="increaseCount()" style="width: 30px; height: 30px; display: flex; align-items: center; justify-content: center;">
                           <i class="bi bi-plus" style="line-height: 1;"></i>
                        </button>
                     </div>
                  </div>
        
               </div>
               <div class="col-6">
                  <h6 class="mob-text">{{ item.total_price|intcomma }} Kč</h6>
               </div>
            </div>
         </form>
         
      </div>
      {% endwith %}
      {% endfor %}
      <div class="row d-flex py-2 justify-content-center border-top">
         <div class="row text-right" style="text-align: right;">
            <h6 class="mob-text">Total: {{ cart.get_total_price|intcomma }} Kč</h6>
         </div>
      </div>
   </div>

   <div>
     
      <p>Máte slevový kód?</p>
      <form action="{% url 'coupons:apply' %}" method="post">
         {{ coupon_form }}
         <input type="submit" value="Apply">
         {% csrf_token %}
      </form>
   </div>

   <section class="jumbotron text-center">
      <div class="container">
         <a href="{% url 'orders:new_order' %}" type="submit" class="btn btn-dark my-2">Koupit</a>
      </div>
   </section>

   {% else %}
   Prozatím zde nic není. Vyberte si z katalogu.
   {% endif %}
   
</div>


<script>
   // update-quantity-code
   var quantityInput = document.getElementById('id_quantity');

   quantityInput.addEventListener('change', function() {
     document.getElementById('id_override').value = 'True';
     document.getElementById('obvod_hrudnik').textContent = this.value;
     document.getElementById('obvod_prsa').textContent = this.value;
     document.getElementById('zpusob_vyroby').textContent = this.value;
     document.getElementById('update-quantity-form').submit();
   });

   function decreaseCount() {
     var input = document.getElementById('id_quantity');
     var value = parseInt(input.value);
     if (value > 1) {
       input.value = value - 1;
     }
     document.getElementById('id_override').value = 'True';
     document.getElementById('obvod_hrudnik').textContent = input.value;
     document.getElementById('obvod_prsa').textContent = input.value;
     document.getElementById('zpusob_vyroby').textContent = input.value;
     document.getElementById('update-quantity-form').submit();
   }

   function increaseCount() {
     var input = document.getElementById('id_quantity');
     var value = parseInt(input.value);
     input.value = value + 1;
     document.getElementById('id_override').value = 'True';
     document.getElementById('obvod_hrudnik').textContent = input.value;
     document.getElementById('obvod_prsa').textContent = input.value;
     document.getElementById('zpusob_vyroby').textContent = input.value;
     document.getElementById('update-quantity-form').submit();
   }
</script>
{% endblock %}