efir/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("pridat/<int:product_id>", views.cart_add, name="cart_add"),
    path("odebrat/<int:product_id>", views.cart_remove, name="cart_remove"),
    path("clean_cart_session", views.clean_cart_session, name="clean_cart_session"),
    path(
        "update_cart_quantity/<str:item_id>",
        views.update_cart_quantity,
        name="update_cart_quantity",
    ),
    path("detail", views.cart_detail, name="cart_detail"),
    path("update_cart_country/", views.update_cart_country, name="update_cart_country"),
]

efir/catalog/urls.py
from django.urls import path

from . import views

app_name = "catalog"

urlpatterns = [
    path("", views.home, name="home"),
    path("kontakty", views.kontakty, name="kontakty"),
    path("doprava", views.doprava, name="doprava"),
    path("reklamace", views.reklamace, name="reklamace"),
    path("rozmery", views.rozmery, name="rozmery"),
    path("ochrana-osobnich-udaju", views.ochrana, name="ochrana"),
    path("obchodni-podminky", views.obchodni_podminky, name="obchodni_podminky"),
    path("o-nas", views.about, name="about"),
    path("discover_your_set", views.discover_your_set, name="discover_your_set"),
    path("objednat_na_miru", views.objednat_na_miru, name="objednat_na_miru"),
    path("product_feed", views.product_feed, name="product_feed"),
    path(
        "delete_all_filters",
        views.delete_all_filters,
        name="delete_all_filters",
    ),  # The issue may be related to the URL configuration. The URL pattern <slug:category_slug> is defined before the pattern <int:id>/<slug:slug>. When you try to access a URL like http://127.0.0.1:8000/delete_existing_filters, it matches the <slug:category_slug> pattern, causing Django to look for a category with the slug "delete_existing_filters," which likely doesn't exist. To fix this issue, you can rearrange your URL patterns, moving the pattern for delete_existing_filters above the category-related patterns. Here's an updated version:
    path("save_filters/", views.save_filters, name="save_filters"),
    path(
        "delete_selected_filter/",
        views.delete_selected_filter,
        name="delete_selected_filter",
    ),
    path("katalog", views.catalog_product_list, name="katalog_vse"),
    path("akce", views.akce, name="akce"),
    path("certifikaty", views.certificates, name="certificates"),
    path(
        "<slug:category_slug>",
        views.catalog_product_list,
        name="product_list_by_category",
    ),
    path("train_the_model/", views.train_the_model, name="train_the_model"),
    path(
        "recommendation_engine/",
        views.recommendation_engine_settings,
        name="recommendation_engine_settings",
    ),
    path(
        "media/assets/Reklamace.pdf",
        views.download_reklamacni_formular,
        name="download_reklamacni_formular",
    ),
    path("<int:id>/<slug:slug>", views.product_detail, name="product_detail"),
]

efir/newsletter/urls.py
from django.urls import path

from . import views

app_name = "newsletter"

urlpatterns = [
    path("subscribe", views.subscribe, name="subscribe"),
    path("unsubscribe", views.unsubscribe, name="unsubscribe"),
    path("subscribe_test", views.subscribe_test, name="subscribe_test"),
]

efir/newsletter/models.py
from django.db import models

# Create your models here.


class Newsletter(models.Model):
    email = models.CharField(max_length=50, verbose_name="Email", editable=False)
    saved_when = models.DateTimeField(
        auto_now_add=True, verbose_name="Přihlášeno", editable=False
    )
    active = models.BooleanField(default=True)

efir/newsletter/forms.py
from django import forms
from django.core.validators import EmailValidator
from django_recaptcha.fields import ReCaptchaField


class SubscribeForm(forms.Form):
    captcha = ReCaptchaField()

    email = forms.EmailField(
        max_length=50,
        validators=[EmailValidator()],
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": "Vložte Váš email, který bežně používáte...",
            }
        ),
    )



class UnsubscribeForm(forms.Form):
    # captcha = ReCaptchaField()

    email = forms.EmailField(
        max_length=50,
        validators=[EmailValidator()],
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": "Vložte Váš email, který chcete smazat...",
            }
        ),
    )

efir/newsletter/views.py
import logging
import ssl

from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string

from .forms import SubscribeForm, UnsubscribeForm
from .models import Newsletter

# Create your views here.


def subscribe_test(request):
    return render(request, "newsletter/subs_conf.html")

def unsubscribe(request):
    Newsletter.objects.all()
    unsubscribe_form = UnsubscribeForm(request.POST)


    if request.method == "POST":
        if unsubscribe_form.is_valid():

            email = unsubscribe_form.cleaned_data["email"]

            if Newsletter.objects.filter(email=email).exists():
                Newsletter.objects.filter(email=email).delete()
                return redirect(reverse('unsubscribe'))


            else:
                return HttpResponse("Email doesn't exist")
        
    return render(request, "newsletter/unsubscribe.html", {"unsubscribe_form": unsubscribe_form})
 


def subscribe(request):
    if request.method == "POST":
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            # Validate reCAPTCHA
            if subscribe_form.cleaned_data.get('captcha'):
                email = subscribe_form.cleaned_data.get("email")

                if not Newsletter.objects.filter(email=email).exists():
                    Newsletter.objects.create(email=email)
                    logging.info(
                        f"Email {email} has been saved and sent subscribe confirmation"
                    )
                    try:
                        customer_order_email_confirmation(email)

                    except ssl.SSLCertVerificationError:
                        logging.info(
                            "Local environment has no email backend set up. Email: {email}"
                        )

                    return render(request, "newsletter/subs_completed.html")

                else:
                    logging.info("Email already exists in the database.")
                    return HttpResponse("Email already exists in the database.")
            else:
                return HttpResponse("reCAPTCHA validation failed")
        else:
            return HttpResponse("Form is not valid")
    else:
        subscribe_form = SubscribeForm()
    return render(request, "subscribe.html", {"subscribe_form": subscribe_form})

def customer_order_email_confirmation(email):
    # html_content = render_to_string("newsletter/subscribe.html")
    html_content = render_to_string("newsletter/subs_conf.html")
    msg = EmailMultiAlternatives(
        subject=("Děkujeme za přihlášení k odběru newsletteru od EFIR"),
        from_email="objednavky@efirthebrand.cz",
        to=[email, "objednavky@efirthebrand.cz"],
    )
    msg.attach_alternative(html_content, "text/html")
    return msg.send()


"""Předmět: Děkujeme za přihlášení k odběru newsletteru od[EFIR

Dobrý den,

rádi bychom Vás srdečně přivítali v naší komunitě a poděkovali za Vaše přihlášení k odběru našeho newsletteru. Je pro nás ctí, že jste se rozhodli být součástí naší české značky ručně šitého spodního prádla EFIR the brand. 

Newsletter Vám bude posílán s osobními nabídkami, exkluzivními slevami pro naše věrné zákazníky a spoustou dalších užitečných informací, které věříme, že Vás budou potěšit. Avšak nechceme Vás otravovat a budeme posílat pouze relevantní a přínosné informace.

Pokud byste měli jakékoliv dotazy, připomínky nebo náměty, neváhejte nás kontaktovat. Jsme tu pro Vás.

Děkujeme Vám ještě jednou za Vaši důvěru a těšíme se na naši budoucí spolupráci.

S pozdravem,

Valérie

Majitelka a hlavní návrhářka 
EFIR the brand"""


"""ion", [])
    size_selection_session = request.session.get("size_selection_session", [])
    sort_by_price_session = request.session.get("sort_by_price_session", "created")
    cut_selection_session = request.session.get("cut_selection_session", [])
    category_session = request.session.get("category_session", [])

    # these are session contents
    # print(show_session_contents(request))

    query_filters = Q()

    if category_session:
        query_filters &= Q(category__name=category_session[0])

    if cut_selection_session:
        if type(cut_selection_session) == str:
            if cut_selection_session == "Brazilky":
                # Filter for products containing "Brazilky" but exclude those containing "Brazilky na gumičkách"
                query_filters &= Q(short_description__icontains="Brazilky")
                query_filters &= ~Q(
                    short_description__icontains="Brazilky na gumičkách"
                )
            elif cut_selection_session == "Podprsenka s kosticemi":
                # Filter for products containing "Brazilky" but exclude those containing "Brazilky na gumičkách"
                query_filters &= Q(
                    short_description__icontains="Podprsenka s kosticemi"
                )
                query_filters &= ~Q(
                    short_description__icontains="Podprsenka s kosticemi a otevřeným košíčkem"
                )

            else:
                query_filters &= Q(short_description__icontains=cut_selection_session)
        else:
            pass

    if zpusob_vyroby_session:
        query_filters &= Q(
            zpusob_vyroby__size=zpusob_vyroby_session[0]
        )  # Assuming zpusob_vyroby is a list

    if size_selection_session:
        query_filters &= Q(inventory__size__in=size_selection_session)

    if sort_by_price_session == ([] or None):
        sort_by_price_session = "created"
    elif type(sort_by_price_session) == str:
        sort_by_price_session = sort_by_price_session

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)

        products = (
            products.filter(category=category)
            .filter(query_filters)
            .order_by(sort_by_price_session)
        )

    else:
        products = (
            Product.objects.filter(query_filters)
            .order_by(sort_by_price_session)
            .filter(active=True)
        )

    sum_of = len(products)

    selected_sizes = clean_session_names(size_selection_session)
    selected_zpubob_vyroby = clean_session_names(zpusob_vyroby_session)
    selected_sorting = clean_session_names(sort_by_price_session)
    selected_cuts = clean_session_names(cut_selection_session)
    selected_category = clean_session_names(category_session)

    return render(
        request,
        "catalog/catalog.html",
        {
            "category": category,
            "categories": categories,
            "products": products,
            "inventory": inventory,
            "filter_form": filter_form,
            "selected_sizes": selected_sizes,
            "selected_zpubob_vyroby": selected_zpubob_vyroby,
            "selected_sorting": selected_sorting,
            "selected_cuts": selected_cuts,
            "selected_category": selected_category,
            "sum_of": sum_of,
        },
    )


def clean_session_names(session_values):
    clean_translation_dict = {
        "price": "Cena vzestupně",
        "-price": "Cena sestupně",
        "name": "Název A-Z",
        "-name": "Název Z-A",
        "created": "Nejnovější",
    }

    for key in clean_translation_dict:
        if key == session_values:
            session_values = clean_translation_dict[key]

    return (
        str(session_values)
        .replace("'", "")
        .replace("[", "")
        .replace("]", "")
        .replace("[", "")
        .replace("]", "")
    )


def delete_all_filters(request):
    if request.method == "POST":
        print("Before Deletion:", request.session.items())

        to_delete = [
            "size_selection_session",
            "cut_selection_session",
            "category_session",
        ]
        for key in to_delete:
            if key in request.session:
                del request.session[key]

        if "sort_by_price_session" in request.session:
            request.session["sort_by_price_session"] = "created"

        print("After Deletion:", request.session.items())

    return redirect("catalog:katalog_vse")


def delete_selected_filter(request):
    if request.method == "POST":
        clean_translation_dict = {
            "Cena vzestupně": "price",
            "Cena sestupně": "-price",
            "Název A-Z": "name",
            "Název Z-A": "-name",
        }

        selected_filter = request.POST.get("selected_filter")

        if selected_filter in clean_translation_dict:
            selected_filter = clean_translation_dict[selected_filter]
            if "sort_by_price_session" in request.session:
                request.session["sort_by_price_session"] = "created"

        for session_key, session_value in request.session.items():
            if isinstance(session_value, (list, str)):
                if selected_filter in session_value:
                    print("session_key", session_key)
                    print("selected filter:", selected_filter)

        del request.session[session_key]

    return redirect("catalog:katalog_vse")


def product_detail(
    request,
    id,
    slug,
):
    categories = (
        Category.objects.all()
    )  # this is only for the purpose of showing the variable in the menu and footer
    product = get_object_or_404(Product, id=id, slug=slug)
    form = CartAddProductForm(id_from_product=id)

    recommended = recommended_products(product_id=id)
    print(
        f"this is the product id of the product {product.name}, {id} and recommended products  {recommended}"
    )

    if str(product.category) == "Dárkové certifikáty":
        pass

    try:
        productset = ProductSet.objects.get(product=product)
    except ProductSet.DoesNotExist:
        productset = None

    return render(
        request,
        "catalog/product_detail.html",
        {
            "categories": categories,

efir/newsletter/templates/newsletter/subs_completed.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load i18n %}
{% load humanize %}

{% block content %}
<script>
  setTimeout(function() {
      window.location.href = "{% url 'catalog:home' %}";  // Redirect to home page after 2 seconds
  }, 1500);
</script>
<style>
    .na_miru_container {
        max-width: 850px; /* Adjust the width as per your requirement */
        margin: 0 auto; /* Centers the content */
    }

    .centered-content {
        text-align: center; /* Centers the content horizontally */
    }
</style>
<div style="padding-bottom: 10%; padding-top: 5%;">
    <div class="container px-5 px-lg-5 mt-5 centered-content"> <!-- Added centered-content class here -->
        <h1> 
            Děkujeme za přihlášení k odběru newsletteru EFIR
        </h1>
        <br>
        <div class="na_miru_container">
            <p> 
            </p>
        </div>
        <br>
    </div>
</div>

{% endblock %}

efir/newsletter/templates/newsletter/subs_conf.html
{% load static %}
{% load i18n %}
{% load humanize %}
{% block content %}
<head>
  <style>
    .lh-condensed > div {
  display: flex;
  align-items: center;
}

.lh-condensed img {
  max-height: 70px;
  max-width: 27px;
  margin-right: 10px;
}

.lh-condensed h6 {
  margin: 0;
}
    .list-group {
  margin-bottom: 1.5rem;
}

.list-group-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.75rem 1.25rem;
  margin-bottom: -1px;
  border: 1px solid rgba(0, 0, 0, 0.125);
}

.lh-condensed > div {
  display: flex;
  align-items: center;
}

.lh-condensed img {
  max-height: 70px;
  max-width: 27px;
  margin-right: 10px;
}

.lh-condensed h6 {
  margin: 0;
}

.text-muted {
  color: #6c757d;
}

.bg-light {
  background-color: #f8f9fa;
}

.w-100 {
  width: 100%;
}

.text-right {
  text-align: right;
}
.list-group {
  --bs-list-group-color: #212529;
  --bs-list-group-bg: #fff;
  --bs-list-group-border-color: rgba(0, 0, 0, 0.125);
  --bs-list-group-border-width: 1px;
  --bs-list-group-border-radius: 0.375rem;
  --bs-list-group-item-padding-x: 1rem;
  --bs-list-group-item-padding-y: 0.5rem;
  --bs-list-group-action-color: #495057;
  --bs-list-group-action-hover-color: #495057;
  --bs-list-group-action-hover-bg: #f8f9fa;
  --bs-list-group-action-active-color: #212529;
  --bs-list-group-action-active-bg: #e9ecef;
  --bs-list-group-disabled-color: #6c757d;
  --bs-list-group-disabled-bg: #fff;
  --bs-list-group-active-color: #fff;
  --bs-list-group-active-bg: #0d6efd;
  --bs-list-group-active-border-color: #0d6efd;
  display: flex;
  flex-direction: column;
  padding-left: 0;
  margin-bottom: 0;
  border-radius: var(--bs-list-group-border-radius);
}
    
.list-group-item {
  position: relative;
  display: block;
  padding: var(--bs-list-group-item-padding-y) var(--bs-list-group-item-padding-x);
  color: var(--bs-list-group-color);
  text-decoration: none;
  background-color: var(--bs-list-group-bg);
  border: var(--bs-list-group-border-width) solid var(--bs-list-group-border-color);
}
.list-group-item:first-child {
  border-top-left-radius: inherit;
  border-top-right-radius: inherit;
}
.list-group-item:last-child {
  border-bottom-right-radius: inherit;
  border-bottom-left-radius: inherit;
}
.list-group-item.disabled, .list-group-item:disabled {
  color: var(--bs-list-group-disabled-color);
  pointer-events: none;
  background-color: var(--bs-list-group-disabled-bg);
}
.list-group-item.active {
  z-index: 2;
  color: var(--bs-list-group-active-color);
  background-color: var(--bs-list-group-active-bg);
  border-color: var(--bs-list-group-active-border-color);
}
.list-group-item + .list-group-item {
  border-top-width: 0;
}
.list-group-item + .list-group-item.active {
  margin-top: calc(-1 * var(--bs-list-group-border-width));
  border-top-width: var(--bs-list-group-border-width);
}

    
    .table {
  --bs-table-color: var(--bs-body-color);
  --bs-table-bg: transparent;
  --bs-table-border-color: var(--bs-border-color);
  --bs-table-accent-bg: transparent;
  --bs-table-striped-color: var(--bs-body-color);
  --bs-table-striped-bg: rgba(0, 0, 0, 0.05);
  --bs-table-active-color: var(--bs-body-color);
  --bs-table-active-bg: rgba(0, 0, 0, 0.1);
  --bs-table-hover-color: var(--bs-body-color);
  --bs-table-hover-bg: rgba(0, 0, 0, 0.075);
  width: 100%;
  margin-bottom: 1rem;
  color: var(--bs-table-color);
  vertical-align: top;
  border-color: var(--bs-table-border-color);
}
.table > :not(caption) > * > * {
  padding: 0.5rem 0.5rem;
  background-color: var(--bs-table-bg);
  border-bottom-width: 1px;
  box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg);
}
.table > tbody {
  vertical-align: inherit;
}
.table > thead {
  vertical-align: bottom;
}

.table-group-divider {
  border-top: 2px solid currentcolor;
}

.caption-top {
  caption-side: top;
}

.table-sm > :not(caption) > * > * {
  padding: 0.25rem 0.25rem;
}

.table-bordered > :not(caption) > * {
  border-width: 1px 0;
}
.table-bordered > :not(caption) > * > * {
  border-width: 0 1px;
}

.table-borderless > :not(caption) > * > * {
  border-bottom-width: 0;
}
.table-borderless > :not(:first-child) {
  border-top-width: 0;
}

.table-striped > tbody > tr:nth-of-type(odd) > * {
  --bs-table-accent-bg: var(--bs-table-striped-bg);
  color: var(--bs-table-striped-color);
}

.table-striped-columns > :not(caption) > tr > :nth-child(even) {
  --bs-table-accent-bg: var(--bs-table-striped-bg);
  color: var(--bs-table-striped-color);
}

.table-active {
  --bs-table-accent-bg: var(--bs-table-active-bg);
  color: var(--bs-table-active-color);
}

.table-hover > tbody > tr:hover > * {
  --bs-table-accent-bg: var(--bs-table-hover-bg);
  color: var(--bs-table-hover-color);
}
    /* Remove bottom border from table rows and cells */
    table.table td,
    table.table th,
    table.table tr,
    table.table thead,
    table.table tbody {
      border-bottom-width: 0; /* Remove bottom border from table rows and cells */
    }
    table.table {
      border-bottom-width: 0; /* Remove bottom border from the table itself */
    }

table.table td:nth-child(1), table.table th:nth-child(1),
table.table td:nth-child(2), table.table th:nth-child(2) {
  text-align: left;
}
  </style>

  
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>efir</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href='{% static "/assets/img/favicon.png" %}' />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href='{% static "/css/styles.css" %}' rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
    <script>
      const csrftoken = Cookies.get('csrftoken');
    </script>
    
  </head>

<!-- Body -->
 

<!-- test inline css online -->
<!-- https://liveweave.com/# -->
<!-- https://codepen.io/mobify/pen/DRyBoB -->
  
<div class="container px-4 py-5 mx-auto mb-5" style="max-width: 800px; min-height: 400px;">
  <div class="row d-flex justify-content-center">
    
    <div class="container justify-content-center text-center" align="center">
        <a class="navbar-brand" style="margin-top: 10px;" href="{% url 'catalog:home' %}">
          
            <img src="https://live.staticflickr.com/65535/53285987159_99d65a33b9_k.jpg" type="image" height="150" alt="">
          </a>
    </div>
    <div class="container">
    <hr class="my-4">

          <p>
            
            <br>

            <p>Dobrý den, {{ mapping_siti_na_miru.name }}</p><br>
            <p>rádi bychom Vás srdečně přivítali v naší komunitě a poděkovali za Vaše přihlášení k odběru našeho newsletteru. Je pro nás ctí, že jste se rozhodli být součástí naší české značky ručně šitého spodního prádla EFIR the brand. 
            </p>
            <p>Newsletter Vám bude posílán s osobními nabídkami, exkluzivními slevami pro naše věrné zákazníky a spoustou dalších užitečných informací, které věříme, že Vás budou potěšit. Avšak nechceme Vás otravovat a budeme posílat pouze relevantní a přínosné informace.
            </p>
          
            <p>Pokud byste měli jakékoliv dotazy, připomínky nebo náměty, neváhejte nás kontaktovat. Jsme tu pro Vás.
            </p>
            <p>Děkujeme Vám ještě jednou za Vaši důvěru a těšíme se na naši budoucí spolupráci.</p><br><br>
            <p>S pozdravem<br><br>Valérie<br>Majitelka a hlavní designérka EFIR the brand</p>             </p>



            <!-- Dobrý den,




Děkujeme Vám ještě jednou za Vaši důvěru a těšíme se na naši budoucí spolupráci.

S pozdravem,

Valérie

Majitelka a hlavní návrhářka 
EFIR the brand-->
<br>






      

          
    
      
    </div>  
   

        <!-- Total --> 
        </div>
    
    </div>
      








<!-- Footer --> 
<div class="container px-4 mx-auto" style="max-width: 800px">

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:600px;">
  <tr>
      <td align="center">
          <img src="https://live.staticflickr.com/65535/53285987159_99d65a33b9_k.jpg"  height="130" style="display: block; border: 0px;"/>
      </td>
  </tr>
  <tr>
      <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 24px; padding: 5px 0 10px 0;">
          <p style="font-size: 14px; font-weight: 800; line-height: 18px; color: #333333;">
              www.efirthebrand.cz <br>

          </p>
      </td>
  </tr>
  <tr>
      <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 24px;">
          <p style="font-size: 14px; font-weight: 400; line-height: 20px; color: #777777;">
          {% trans "© 2023 efirthebrand. Všechna práva vyhrazena. Tuto zprávu jsme vám poslali, protože jste registrováni na www.efirthebrand.cz pod adresou" %} {{order.email}}. {% trans "Pokud si myslíte, že vám byla poslána omylem nebo vám nevyhovuje četnost našich emailů, můžete se " %}<a href="#" target="_blank" style="color: #777777;">{% trans "odhlásit" %}</a> {% trans "nebo změnit frekvenci zasílání." %}
              <!--If you didn't create an account using this email address, please ignore this email or <a href="#" target="_blank" style="color: #777777;">unsusbscribe</a>.-->
          </p>
      </td>
  </tr>
</table>
<!-- End Body -->
</div>
{% endblock %}

efir/newsletter/templates/newsletter/unsubs_completed.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load i18n %}
{% load humanize %}

{% block content %}
<script>
  setTimeout(function() {
      window.location.href = "{% url 'catalog:home' %}";  // Redirect to home page after 2 seconds
  }, 1500);
</script>
<style>
    .na_miru_container {
        max-width: 850px; /* Adjust the width as per your requirement */
        margin: 0 auto; /* Centers the content */
    }

    .centered-content {
        text-align: center; /* Centers the content horizontally */
    }
</style>
<div style="padding-bottom: 10%; padding-top: 5%;">
    <div class="container px-5 px-lg-5 mt-5 centered-content"> <!-- Added centered-content class here -->
        <h1> 
            Váš email je odhlášen
        </h1>
        <br>
        <div class="na_miru_container">
            <p> 
            </p>
        </div>
        <br>
    </div>
</div>

{% endblock %}

efir/newsletter/templates/newsletter/unsubscribe.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load i18n %}
{% load humanize %}

{% block content %}
<style>
    .na_miru_container {
        max-width: 850px; /* Adjust the width as per your requirement */
        margin: 0 auto; /* Centers the content */
    }

    .centered-content {
        text-align: center; /* Centers the content horizontally */
    }
</style>
<div style="padding-bottom: 10%;">
    <div class="container px-5 px-lg-5 mt-5 centered-content"> <!-- Added centered-content class here -->
        <h1> 

<form id="unsubscribe-form" class="needs-validation" novalidate action="{% url 'newsletter:unsubscribe' %}" method="post">
  {% csrf_token %}
  <h5>Jaký email chcete odhlásit?</h5>
  <div class="d-flex flex-column flex-sm-row w-100 gap-2">
     <input class="form-control" type="email" name="email" id="id_email" placeholder="Email address" required oninput="validateEmail()">
  </div>
  <button class="btn btn-light" type="submit">Odhlásit</button>

<!--  <div class="mt-3">{{ subscribe_form.captcha }}</div>-->
</form>
        </h1>
        <br>
        <div class="na_miru_container">
            <p> 
            </p>
        </div>
        <br>
    </div>
</div>

{% endblock %}