efir/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("pridat/<int:product_id>", views.cart_add, name="cart_add"),
    path("odebrat/<int:product_id>", views.cart_remove, name="cart_remove"),
    path("clean_cart_session", views.clean_cart_session, name="clean_cart_session"),
    path(
        "update_cart_quantity/<str:item_id>",
        views.update_cart_quantity,
        name="update_cart_quantity",
    ),
    path("detail", views.cart_detail, name="cart_detail"),
    path("update_cart_country/", views.update_cart_country, name="update_cart_country"),
]

efir/catalog/urls.py
from django.urls import path

from . import views

app_name = "catalog"

urlpatterns = [
    path("", views.home, name="home"),
    path("kontakty", views.kontakty, name="kontakty"),
    path("doprava", views.doprava, name="doprava"),
    path("reklamace", views.reklamace, name="reklamace"),
    path("rozmery", views.rozmery, name="rozmery"),
    path("ochrana-osobnich-udaju", views.ochrana, name="ochrana"),
    path("obchodni-podminky", views.obchodni_podminky, name="obchodni_podminky"),
    path("o-nas", views.about, name="about"),
    path("discover_your_set", views.discover_your_set, name="discover_your_set"),
    path("objednat_na_miru", views.objednat_na_miru, name="objednat_na_miru"),
    path("product_feed", views.product_feed, name="product_feed"),
    path(
        "delete_all_filters",
        views.delete_all_filters,
        name="delete_all_filters",
    ),  # The issue may be related to the URL configuration. The URL pattern <slug:category_slug> is defined before the pattern <int:id>/<slug:slug>. When you try to access a URL like http://127.0.0.1:8000/delete_existing_filters, it matches the <slug:category_slug> pattern, causing Django to look for a category with the slug "delete_existing_filters," which likely doesn't exist. To fix this issue, you can rearrange your URL patterns, moving the pattern for delete_existing_filters above the category-related patterns. Here's an updated version:
    path("save_filters/", views.save_filters, name="save_filters"),
    path(
        "delete_selected_filter/",
        views.delete_selected_filter,
        name="delete_selected_filter",
    ),
    path("katalog", views.catalog_product_list, name="katalog_vse"),
    path("akce", views.akce, name="akce"),
    path("certifikaty", views.certificates, name="certificates"),
    path(
        "<slug:category_slug>",
        views.catalog_product_list,
        name="product_list_by_category",
    ),
    path("train_the_model/", views.train_the_model, name="train_the_model"),
    path(
        "recommendation_engine/",
        views.recommendation_engine_settings,
        name="recommendation_engine_settings",
    ),
    path(
        "media/assets/Reklamace.pdf",
        views.download_reklamacni_formular,
        name="download_reklamacni_formular",
    ),
    path("<int:id>/<slug:slug>", views.product_detail, name="product_detail"),
]

efir/orders/urls.py
from django.urls import path

from . import views
from .views import *

app_name = "orders"


urlpatterns = [
    path("invoice", views.invoice, name="invoice"),
    path("contact_form", views.contact_form, name="contact_form"),
    path(
        "media/assets/<str:file_name>",
        views.download_ppl_label,
        name="download_ppl_label",
    ),
    path("new", views.new_order, name="new_order"),
    path(
        "send_offer_confirmation/<int:order_id>/",
        views.send_offer_confirmation,
        name="send_offer_confirmation",
    ),
    path(
        "send_paid_offer_confirmation/<int:order_id>/",
        views.send_paid_offer_confirmation,
        name="send_paid_offer_confirmation",
    ),
    path("update_orders", views.update_orders, name="update_orders"),
    path("cleanup_orders", views.cleanup_orders, name="cleanup_orders"),
]

efir/orders/models.py
from decimal import Decimal

from django.conf import settings
from django.db import models
from django.utils import timezone

from catalog.models import Product


class Order(models.Model):
    etb_id = models.CharField(max_length=50, verbose_name="Efir ID")
    first_name = models.CharField(max_length=50, verbose_name="Jméno")
    last_name = models.CharField(max_length=50, verbose_name="Příjmení")
    birthday = models.DateField(verbose_name="Datum narození", null=True, blank=True)
    email = models.CharField(max_length=50, verbose_name="Email")
    number = models.CharField(max_length=20, verbose_name="Telefonní číslo")
    comments = models.TextField(blank=True, verbose_name="Komentáře")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno")
    updated = models.DateTimeField(auto_now=True, verbose_name="Aktualizováno")

    COUNTRY_CHOICES = [("CZ", "cz"), ("SK", "sk")]

    country = models.CharField(max_length=20, verbose_name="Země")
    shipping_type = (  # TODO I need to add new option personal pickup here
        ("", "Vyberte si způsob dopravy"),
        ("P", "PPL"),
        ("D", "PPL - Doručení domů"),
        ("Z", "Zásilkovna"),
        ("O", "Online"),
        ("S", "Osobní odběr"),
    )
    shipping = models.CharField(
        max_length=100,
        choices=shipping_type,
        verbose_name="Doprava",
        default="Zásilkovna",
    )
    shipping_price = models.DecimalField(
        decimal_places=0,
        max_digits=4,
        blank=True,
        default=Decimal("0"),
        verbose_name="Cena dopravy (CZK)",
    )
    address = models.CharField(max_length=250, verbose_name="Adresa", blank=False)
    city = models.CharField(max_length=250, verbose_name="City", blank=True, null=True)
    zipcode = models.CharField(
        max_length=250, verbose_name="Zipcode", blank=True, null=True
    )

    vendor_id = models.CharField(
        max_length=250,
        verbose_name="ID prodejce",
        blank=False,
    )
    discount = models.DecimalField(
        decimal_places=0,
        max_digits=10,
        blank=True,
        default=Decimal("0"),
        verbose_name="Sleva (CZK)",
    )
    total_cost = models.DecimalField(
        decimal_places=2,
        max_digits=10,
        blank=True,
        default=Decimal("0.00"),
        verbose_name="Celková cena (CZK)",
    )

    stripe_id = models.CharField(max_length=250, blank=True, verbose_name="Stripe ID")
    zasilkovna_id = models.CharField(
        max_length=250, blank=True, verbose_name="Zásilkovna ID"
    )
    paid = models.BooleanField(default=False, verbose_name="Zaplaceno")
    shipped = models.BooleanField(default=False, verbose_name="Vyřízeno")
    newsletter_consent = models.BooleanField(
        default=False, verbose_name="Souhlas - newsletter", null=True, blank=True
    )
    author_comment = models.CharField(
        max_length=200, blank=True, verbose_name="ETB poznamka k objednavce"
    )
    discount_code = models.CharField(
        max_length=15, blank=True, default="-", verbose_name="Slevovy kod"
    )
    coupon_id = models.CharField(
        max_length=15, blank=True, default="-", verbose_name="ID certifikatu"
    )
    label = models.CharField(
        max_length=200, blank=True, null=True, verbose_name="Etiketa k doprave"
    )  # Or use FilePathField if you want to restrict to a certain directory

    confirmation_sent = models.BooleanField(
        default=False, verbose_name="Emailove potvrzení objednávky"
    )
    shipped_sent = models.BooleanField(
        default=False, verbose_name="Email předáno k dopravci"
    )

    class Meta:
        verbose_name = "Objednávky"
        verbose_name_plural = "Objednávky"
        ordering = ["-created"]
        indexes = [
            models.Index(fields=["-created"]),
        ]

    def __str__(self):
        return f"Objednávka {self.id}"

    def get_stripe_url(self):
        if not self.stripe_id:
            return ""
        elif "_test_" in settings.STRIPE_SECRET_KEY:
            path = "/test/"
        else:
            path = "/"

        return f"https://dashboard.stripe.com{path}payments/{self.stripe_id}"

    def get_zasilkovna_url(self):
        pass

    def save(self, *args, **kwargs):
        # self.shipping_price = self.calculate_shipping_price()

        if "cart" in kwargs:
            cart = kwargs.pop("cart")
            cart.get_total_price_after_discount()

            self.shipping_price = cart.get_shipping_price()
            self.discount = cart.transfer_discount_to_orders()
            self.total_cost = cart.get_total_price_after_discount()

        if not self.etb_id:
            today_date = timezone.now().strftime("%y%m%d")
            today_order_count = Order.objects.filter(
                created__date=timezone.now().date()
            ).count()
            self.etb_id = f"{today_date}{today_order_count:02d}"

        """ vendor_id = kwargs.pop("vendor_id", None)
        if vendor_id:
            self.vendor_id = vendor_id

        print(f"model order printing vendor_id{vendor_id}")"""

        super().save(*args, **kwargs)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name="order_items", on_delete=models.CASCADE
    )
    price = models.DecimalField(
        decimal_places=0, max_digits=10, verbose_name="Cena za kus (CZK)"
    )
    total_price = models.DecimalField(
        decimal_places=0,
        max_digits=10,
        verbose_name="Cena (CZK)",
        default=0,
    )
    surcharge = models.DecimalField(
        decimal_places=0,
        max_digits=10,
        verbose_name="Příplatek za šití na míru (CZK)",
        default=0,
    )
    quantity = models.PositiveIntegerField(default=1, verbose_name="Množství")

    zpusob_vyroby = models.CharField(max_length=50)
    velikost = models.CharField(
        max_length=50, null=True, blank=True, verbose_name="Individuální velikost"
    )
    kalhotky_velikost_set = models.CharField(max_length=50, null=True, blank=True)
    podprsenka_velikost_set = models.CharField(max_length=50, null=True, blank=True)
    pas_velikost_set = models.CharField(max_length=50, null=True, blank=True)

    poznamka = models.TextField(blank=True)
    slevovy_kod = models.CharField(
        max_length=20, default="-", verbose_name="Slevový kód"
    )
    hodnota_kuponu = models.CharField(
        max_length=20, default="-", verbose_name="Hodnota kuponu"
    )
    certificate_from = models.CharField(
        max_length=100, default="-", verbose_name="Od koho"
    )
    certificate_to = models.CharField(max_length=100, default="-", verbose_name="Komu")

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

efir/orders/views.py
import logging
import mimetypes
import os

from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from .mail_confirmation import *
from .models import Order

# Set up the logging configuration
logging.basicConfig(level=logging.DEBUG)

""


# todo this can be deleted
def new_order(request):
    pass
    ''' cart = Cart(request)

    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(
                commit=False
            )  # In this line, you are using a Django ModelForm (order_form) to create an Order instance. The commit=False argument prevents the instance from being saved to the database immediately. Instead, it returns an unsaved instance of the model. This allows you to make additional modifications to the instance before saving it to the database.
            order.save(cart=cart)
            """Once you have the unsaved order instance, you can call its save method to save it to the database. In this case, you are passing an additional keyword argument cart to the save method. This is where you are providing the cart instance to the save method of the Order model.
            In the save method of the Order model, you are accessing the cart instance through this passed keyword argument to calculate the total_cost for the order. This is a way to pass contextual information from the view (the cart instance) to the model (Order instance) when saving it.
            The combination of these lines ensures that the Order instance is created from the form data but not immediately saved, allowing you to calculate and set additional fields like total_cost before the final save."""

            order_form_data = {
                "order_id": order.id,
                "country": order.country,
                # Add any other data you want to include here...
            }

            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item["product"],
                    price=item["price"],
                    quantity=item["quantity"],
                    velikost=item["velikost"],
                )

            # clear the cart

            cart.clear()

            request.session["order_id"] = order.id

            try:
                order_id = order.id
                zasilkovna_create_package(order_id)
                customer_order_email_confirmation(order_id)

            except ssl.SSLCertVerificationError:
                logging.info(
                    f"Local environment has no email backend set up.Order ID: {order_id}"
                )

            # return render(request, "orders/objednavka_vytvorena.html", {"order": order})
            return redirect(reverse("stripepayment:process"))
    else:
        form = OrderForm()

    return render(
        request,
        "orders/new.html",
        {"cart": cart, "form": form, order_form_data: "order_form_data"},
    )
'''


def calculate_shipping_price(country_code):
    if country_code == "CZ":
        return 79
    elif country_code == "SK":
        return 89
    elif country_code == "EK":
        return 0
    else:
        return 0
    # Add other country prices here


def invoice(request):
    id = 413
    order = get_object_or_404(Order, id=id)
    print(order)
    return render(request, "orders/order_shipped.html", {"order": order})

    order = get_object_or_404(Order, id=id)

    print(order)
    return render(request, "orders/certificate_confirmation.html", {"order": order})


def update_orders(request):
    selected_order = Order.objects.filter(id=939)
    selected_order.update(discount=-300, total_cost=2029)
    return HttpResponse("Order has been corrected")


def contact_form(request):
    return render(request, "orders/contact_form.html")


def download_ppl_label(request, file_name):
    # file_path = "media/assets/Reklamace.pdf"  # URL to your file

    file_path = os.path.join(
        settings.MEDIA_ROOT, "catalog/ppl_labels", file_name + ".pdf"
    )
    fl = open(file_path, "rb")
    mime_type, _ = mimetypes.guess_type(file_path)
    response = HttpResponse(fl, content_type=mime_type)
    response["Content-Disposition"] = "attachment; filename=%s" % file_name
    return response


def cleanup_orders(request):
    Order.objects.filter(shipped=True).update(shipped_sent=True)
    return HttpResponse("orders cleaned up")

efir/orders/templates/orders/backups/customer_email_confirmation copy.html
{% load static %}
{% load i18n %}
{% load humanize %}
{% block content %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>efir</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href='{% static "/assets/img/favicon.png" %}' />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href='{% static "/css/styles.css" %}' rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
    <script>
      const csrftoken = Cookies.get('csrftoken');
    </script>
    
  </head>

<!-- Body -->
<div class="container px-4 py-5 mx-auto mb-5" style="max-width: 800px; min-height: 400px;">
  <div class="row d-flex justify-content-center">
    
    <div class="container justify-content-center text-center">
        <a class="navbar-brand" style="margin-top: 10px;" href="{% url 'catalog:home' %}">
            <img src="https://www.linkpicture.com/q/logo_99.png" height="50" alt="">
          </a>
    </div>
    <div class="container">
    <hr class="my-4">

          <p>
            {{ order.first_name }},<br>
            <br>
            
            Vaše objednávka #{{order.id}} nám byla doručena. Budeme se ji snažit zpracovat v co nejkratší době.
            
            Toto je automaticky generované potvrzení objednávky. Pokud máte jakékoli dotazy týkající se vaší objednávky, odepište, prosím, zpět na tento email.
            
             </p>

             <!-- new sqr-->
             <div class="table-container"> <!-- Apply margins to the table container -->

              <table class="table mt-4"> <!-- Create a table -->
                  <colgroup>
                      <col style="width: 16.67%;">
                      <col style="width: 16.67%;">
            
                  </colgroup>
                  <thead>
                      <th>Obvod pod prsama</th>
                      <th colspan="5" class="text-center">Prsa, cm</th>
                   
                  </thead>
                  <tbody>
                      <tr>
                          <td>1</td>
                          <td>2</td>
                     
                      </tr>
                      <tr>
                          <td>7</td>
                          <td>8</td>
                  
                      </tr>
                      <tr>
                          <td>13</td>
                          <td>14</td>
                          <td>15</td>
                          <td>16</td>
                          <td>17</td>
                          <td>18</td>
                      </tr>
                      <tr>
                          <td>19</td>
                          <td>20</td>
                          <td>21</td>
                          <td>22</td>
                          <td>23</td>
                          <td>24</td>
                      </tr>
                      <tr>
                          <td>25</td>
                          <td>26</td>
                          <td>27</td>
                          <td>28</td>
                          <td>29</td>
                          <td>30</td>
                      </tr>
                      <tr>
                          <td>31</td>
                          <td>32</td>
                          <td>33</td>
                          <td>34</td>
                          <td>35</td>
                          <td>36</td>
                      </tr>
                  </tbody>
              </table>
              </div>
              
             <tr>
              <td align="left" style="padding-top: 20px;">
                  <table cellspacing="0" cellpadding="0" border="0" width="50%">
                      <tr>
                          <td width="75%" align="left" bgcolor="#ffffff" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 800; line-height: 24px; padding: 10px;">
                            Vaše objednávka # {{ order.id }}                              
            
                          </td>
                          <td width="25%" align="left" bgcolor="#ffffff" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 800; line-height: 24px; padding: 10px;">
                         
                          </td>
                      </tr>
                      <tr> 

                          <td width="75%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;">
                            <h6 class="mob-text">Vaše jméno:</h6>
                    
                          </td>
                          <td width="25%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;">
                            <p class="mob-text"> {{ order.first_name }} {{ order.last_name }}</p>
                          </td>
                      </tr>
                      <tr>
                        <td width="75%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;">
                          <h6 class="mob-text">Email:</h6>
                  
                        </td>
                        <td width="25%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;">
                          <p class="mob-text"> {{ order.email }}</p>
                        </td>
                      </tr>
                      <tr>
                        <td width="75%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;">
                          
                            <h6 class="mob-text">Doručovací adresa:</h6>
                          
                    </h6>
                  
                        </td>
                        <td width="25%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;">
                          <p class="mob-text"> {{ order.address }}</p>
                        </td>
                      </tr>
                      <tr>
                        <td width="75%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;">
                          <h6 class="mob-text"> Způsob dopravy:</h6>
         
                  
                        </td>
                        <td width="25%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;">
                          <p class="mob-text">     {{ order.get_shipping_display }}</p>
                        </td>
                      </tr>
                      <tr>
                        <td width="75%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;">
                          <h6 class="mob-text">Telefonní číslo:</h6>
                  
                        </td>
                        <td width="25%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;">
                          <p class="mob-text"> {{ order.number }}</p>
                        </td>
                      </tr>
                      <tr>
                        <td width="75%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;">
                          <h6 class="mob-text">Poznámka:</h6>
                  
                        </td>
                        <td width="25%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;">
                          <p class="mob-text"> {{ order.comments }}</p>
                        </td>
                      </tr>
                      <tr>
                        <td width="75%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;">
                          <h6 class="mob-text">Doprava:</h6>
                  
                        </td>
                        <td width="25%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;">
                          <p class="mob-text"> {{ order.shipping }}</p>
                        </td>
                      </tr>
                      <tr>
                        <td width="75%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;">
                          <h6 class="mob-text">Celkem:</h6>
                  
                        </td>
                        <td width="25%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;">
                          <p class="mob-text"> {{ order.total_cost }}</p>
                        </td>
                      </tr>
                         
                      </tr>
                  </table>
              </td>
          </tr>

  
        </table>
    </div>  
    <br>
                <!-- Shopping Cart Section -->
              <div class="row">
                  <h4 class="d-flex justify-content-between align-items-center mb-3">
                    
                  
                
              <!-- 2cart -->
           
              <a href="{% url 'catalog:katalog_vse' %}"><button class="btn btn-dark my-2 mb-4">Do obchodu</button></a>
             
              </div>
          
    
      </div>
      
  </div>
  <!-- whole product-->

  



  </div>
</div>

<script>
  function decreaseCount() {
      var input = document.getElementById("inputQuantity");
      var value = parseInt(input.value);
      if (value > 1) {
          input.value = value - 1;
      }
  }

  function increaseCount() {
      var input = document.getElementById("inputQuantity");
      var value = parseInt(input.value);
      input.value = value + 1;
  }

</script>
<div class="container px-4 py-5 mx-auto" style="max-width: 800px">

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:600px;">
  <tr>
      <td align="center">
          <img src="https://www.linkpicture.com/q/logo_99.png"  height="50px" style="display: block; border: 0px;"/>
      </td>
  </tr>
  <tr>
      <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 24px; padding: 5px 0 10px 0;">
          <p style="font-size: 14px; font-weight: 800; line-height: 18px; color: #333333;">
              www.efirthebrand.cz <br>

          </p>
      </td>
  </tr>
  <tr>
      <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 24px;">
          <p style="font-size: 14px; font-weight: 400; line-height: 20px; color: #777777;">
          {% trans "© 2023 efirthebrand. Všechna práva vyhrazena. Tuto zprávu jsme vám poslali, protože jste registrováni na www.efirthebrand.cz pod adresou" %} {{order.email}}. {% trans "Pokud si myslíte, že vám byla poslána omylem nebo vám nevyhovuje četnost našich emailů, můžete se " %}<a href="#" target="_blank" style="color: #777777;">{% trans "odhlásit" %}</a> {% trans "nebo změnit frekvenci zasílání." %}
              <!--If you didn't create an account using this email address, please ignore this email or <a href="#" target="_blank" style="color: #777777;">unsusbscribe</a>.-->
          </p>
      </td>
  </tr>
</table>
<!-- End Body -->
</div>
{% endblock %}