efir/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("pridat/<int:product_id>", views.cart_add, name="cart_add"),
    path("odebrat/<int:product_id>", views.cart_remove, name="cart_remove"),
    path("clean_cart_session", views.clean_cart_session, name="clean_cart_session"),
    path(
        "update_cart_quantity/<str:item_id>",
        views.update_cart_quantity,
        name="update_cart_quantity",
    ),
    path("detail", views.cart_detail, name="cart_detail"),
    path("update_cart_country/", views.update_cart_country, name="update_cart_country"),
]

efir/catalog/urls.py
from django.urls import path

from . import views

app_name = "catalog"

urlpatterns = [
    path("", views.home, name="home"),
    path("kontakty", views.kontakty, name="kontakty"),
    path("doprava", views.doprava, name="doprava"),
    path("reklamace", views.reklamace, name="reklamace"),
    path("rozmery", views.rozmery, name="rozmery"),
    path("ochrana-osobnich-udaju", views.ochrana, name="ochrana"),
    path("obchodni-podminky", views.obchodni_podminky, name="obchodni_podminky"),
    path("o-nas", views.about, name="about"),
    path("discover_your_set", views.discover_your_set, name="discover_your_set"),
    path("objednat_na_miru", views.objednat_na_miru, name="objednat_na_miru"),
    path("product_feed", views.product_feed, name="product_feed"),
    path(
        "delete_all_filters",
        views.delete_all_filters,
        name="delete_all_filters",
    ),  # The issue may be related to the URL configuration. The URL pattern <slug:category_slug> is defined before the pattern <int:id>/<slug:slug>. When you try to access a URL like http://127.0.0.1:8000/delete_existing_filters, it matches the <slug:category_slug> pattern, causing Django to look for a category with the slug "delete_existing_filters," which likely doesn't exist. To fix this issue, you can rearrange your URL patterns, moving the pattern for delete_existing_filters above the category-related patterns. Here's an updated version:
    path("save_filters/", views.save_filters, name="save_filters"),
    path(
        "delete_selected_filter/",
        views.delete_selected_filter,
        name="delete_selected_filter",
    ),
    path("katalog", views.catalog_product_list, name="katalog_vse"),
    path("akce", views.akce, name="akce"),
    path("certifikaty", views.certificates, name="certificates"),
    path(
        "<slug:category_slug>",
        views.catalog_product_list,
        name="product_list_by_category",
    ),
    path("train_the_model/", views.train_the_model, name="train_the_model"),
    path(
        "recommendation_engine/",
        views.recommendation_engine_settings,
        name="recommendation_engine_settings",
    ),
    path(
        "media/assets/Reklamace.pdf",
        views.download_reklamacni_formular,
        name="download_reklamacni_formular",
    ),
    path("<int:id>/<slug:slug>", views.product_detail, name="product_detail"),
]

efir/catalog/forms.py
from django import forms
from django.core.validators import EmailValidator
from django_recaptcha.fields import ReCaptchaField

from catalog.models import Category, Product
from inventory.models import Inventory


class ContactForm(forms.Form):
    captcha = ReCaptchaField()

    name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Vaše jméno"}
        ),
    )
    email = forms.EmailField(
        max_length=50,
        validators=[EmailValidator()],
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "Email"}
        ),
    )
    message = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control", "placeholder": "Text"}),
        required=True,
    )


class FilterForm(forms.Form):
    def custom_sort(size):
        if size[:-1].isdigit():
            return int(size[:-1]), size[-1]
        else:
            return float("inf"), size

    def prioritize_sizes(n):
        knickers_dict = {
            "XS": 1,
            "S": 2,
            "M": 3,
            "L": 4,
            "XL": 5,
        }

        knickers = []
        bras = []
        for size in n:
            if size in knickers_dict:
                knickers.append(size)
            else:
                bras.append(size)

        knickers.sort(key=lambda x: knickers_dict[x])

        print(knickers)
        return knickers + bras

    all_sizes = Inventory.objects.all()
    all_sizes = all_sizes.distinct()
    all_sizes = all_sizes.values_list("size")
    letters_only = [size[0].strip("()") for size in all_sizes if size[0]]
    sorted_sizes = sorted(letters_only, key=custom_sort)
    resorted_sizes = prioritize_sizes(sorted_sizes)
    tuple_sizes = [(size, size) for size in resorted_sizes]
    print("size_choices:", resorted_sizes)

    products = Product.objects.all()

    cuts_all = products.values_list("short_description").distinct()
    cuts_letters_only = [x[0].strip("()") for x in cuts_all if x[0]]
    cuts_all_list = set(cuts_letters_only)
    cut_choices = [(i, i) for i in cuts_all_list]

    cut_choices_manual = [
        ("Brazilky", "Brazilky"),
        ("Brazilky na gumičkách", "Brazilky na gumičkách"),
        ("V-string", "V-string"),
        ("Vysoká tanga", "Vysoká tanga"),
        ("Podvazkový pas s gumičkami", "Podvazkový pas s gumičkami"),
        ("Bezkosticová podprsenka", "Bezkosticová podprsenka"),
        ("Podprsenka s kosticemi", "Podprsenka s kosticemi"),
        (
            "Podprsenka s kosticemi a otevřeným košíčkem",
            "Podprsenka s kosticemi a otevřeným košíčkem",
        ),
    ]

    categories = Category.objects.all()
    categories = categories.values_list("name").distinct()
    categories = [name[0].strip("()") for name in categories]
    categories = [(i, i) for i in categories]

    size_selection = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=tuple_sizes,
        label="Velikost",
        required=False,
    )

    sorting_choices = [
        ("price", "Cena vzestupně"),
        ("-price", "Cena sestupně"),
        ("name", "Název A-Z"),
        ("-name", "Název Z-A"),
    ]

    sort_by_price = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=sorting_choices,
        label="Radit podle",
        required=False,
    )

    zpusob_vyroby_choices = [
        ("Skladem", "Skladem"),
        ("Na Míru", "Na Míru"),
    ]

    zpusob_vyroby = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=zpusob_vyroby_choices,
        label="Zpusob vyroby",
        required=False,
    )

    cut_selection = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=cut_choices_manual,
        label="Volba střihu",
        required=False,
    )

    category_selection = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=categories,
        label="Volba kategorie",
        required=False,
    )


class CreateSetForm(forms.Form):
    # captcha = ReCaptchaField()

    name = forms.CharField(
        label="Vaše jméno",
        max_length=50,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )

    surname = forms.CharField(
        label="Vaše příjmení",
        max_length=50,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    email = forms.EmailField(
        max_length=50,
        validators=[EmailValidator()],
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": "Email, který bežně používáte...",
            }
        ),
    )
    # opravit
    birthday = forms.DateField(
        label="Kdy jste se narodila?",
        widget=forms.DateInput(attrs={"class": "form-control"}),
    )

    hair_color = forms.ChoiceField(
        choices=[(i, i) for i in range(1, 9)],
        label="Jakou máte barvu vlasů:",
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    skin_color = forms.ChoiceField(
        choices=[(i, i) for i in range(1, 7)],
        label="Který odstín kůže na obrázku je nejvíce podobný té vaší:",
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    color_tone = forms.ChoiceField(
        choices=[
            (i, i)
            for i in [
                "Neutrální barvy (černá, bílá, béžová)",
                "Pastelové tóny (růžová, světlé modrá, levandule)",
                "Tmavší tóny (tmavě modrá, smaragdová, bordo)",
                "Výrazné barvy (červená, lavandule, tyrkysová)",
            ]
        ],
        label="Jaký je váš oblíbený barevný odstín, ve kterém se cítíte nejlépe?",
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    colors_to_avoid = forms.ChoiceField(
        choices=[(i, i) for i in ["Neexistují", "Jiné"]],
        label="Existují barvy, kterým se snažíte vyhýbat?",
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    other_colors = forms.CharField(
        label="Jiné barvy, kterým se snažíte vyhýbat:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "kterou nikdy nevyberete na spodní prádlo...",
            }
        ),
    )

    def set_other_colors(self):
        colors_to_avoid = self.cleaned_data.get("colors_to_avoid", None)

        if colors_to_avoid != "Jiné":
            self.cleaned_data["other_colors"] = "-"

    design_preferences = forms.ChoiceField(
        choices=[
            (i, i)
            for i in [
                "Jednoduchý a elegantní",
                "S decentními vzory",
                "S výraznými vzory a detaily",
            ]
        ],
        label="Máte raději jednoduchý a elegantní design, nebo preferujete spodní prádlo s výraznými vzory a detaily?",
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    overall_fitness = forms.ChoiceField(
        choices=[
            (i, i)
            for i in [
                "Ano, je to pro mě důležité",
                "Někdy, záleží na příležitosti",
                "Ne, spodní prádlo je pro mě samostatným prvkem",
            ]
        ],
        label="Když si vybíráte spodní prádlo, berete v potaz, jak ladí s vaším běžným oblečením?",
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    individual_cut = forms.ChoiceField(
        choices=[
            (i, i)
            for i in [
                "Pohodlí má pro mě prioritu",
                "Obojí, ideálně kombinace pohodlí a stylu",
                "Styl je pro mě klíčový",
            ]
        ],
        label="Je pro vás důležitý pohodlný střih, nebo upřednostňujete spodní prádlo, které zdůrazňuje váš individuální styl?",
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    knickers_cut = forms.ChoiceField(
        choices=[(i, i) for i in ["Brazilky", "Tanga", "Slipy"]],
        label="Který střih kalhotek je pro Vás nejpohodlnější?",
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    bra_cut = forms.ChoiceField(
        choices=[
            (i, i)
            for i in [
                "Podprsenka s kosticemi",
                "Podprsenka bez kostic",
                "Podprsenka s výrazným střihem",
            ]
        ],
        label="Který střih podprsenky poskytuje komfortní nošení?",
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    activities = forms.ChoiceField(
        choices=[
            (i, i)
            for i in [
                "Každodenní nošení",
                "Při sportovních aktivitách",
                "Speciální příležitosti",
            ]
        ],
        label="V jakých příležitostech nosíte spodní prádlo nejčastěji?",
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    preferred_details = forms.CharField(
        required=False,
        label="Existují nějaké specifické vlastnosti nebo detaily, na které jste zvyklá a které byste chtěla u vysněného setu? (volná odpověď)",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Oceníme každé slovo..."}
        ),
    )

    gdpr_consent = forms.BooleanField(
        label="Souhlas se zpracováním osobních údajů.",
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}),
    )
    newsletter_consent = forms.BooleanField(
        label="Souhlas s odebíráním newsletteru.",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}),
    )

    """
Pak tlačítko odeslat. + tlačítko souhlas se zpracováním osobních údajů, tlačítko s odebráním newslatter (oba jsou povinné zaškrtnout)

efir/catalog/templates/catalog/catalog.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load humanize %}
{% load i18n %}

{% block content %}
<!--Intro, Header Jumbotron --> 
<!-- link here: https://getbootstrap.com/docs/5.3/examples/jumbotron/ -->

{% with category_value=selected_category|default:"Vše" %}
<script>
  lhi('ViewCategory', {
    category: "{{ category_value }}"
  });
</script>
{% endwith %}


<style>
  .dropdown-item.active {
  background-color: #000; /* Set background color to black */
  color: #fff; /* Set text color to white */
}


    .thin-border {
        border: 1px solid black; /* Grey color */
    }

</style>



<!-- Catalog of Products -->
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading mt-5 mb-5">{% if category %}{{category}} </h1>
        {% else %}
        <h1 class="jumbotron-heading mt-5 mb-5">Katalog
        {% endif %}</h1>
    </div>

 <!-- start of other filter dropdowns as needed -->
<div class="filters">
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <script>
     $(document).ready(function() {
       // Event handler for changes in dropdowns
       $('.dropdown-item').click(function() {
         // Find the closest parent with class 'btn-group'
         var parentBtnGroup = $(this).closest('.btn-group');
     
         // Find the dropdown toggle within the 'btn-group'
         var dropdownToggle = parentBtnGroup.find('.dropdown-toggle');
     
         // Get the id attribute of the dropdown toggle
         var dropdownId = dropdownToggle.attr('id');
     
         // Set the value of the dropdown to the selected item's text
         $('#' + dropdownId).val($(this).text());
     
         // Submit the form with id 'save_filters'
         $('#save_filters').submit();
       });
     });
  </script>
  <style>
     #save_filters {
     display: inline-block; /*display: inline-block;: This style makes the form and button groups inline-block elements, allowing them to appear next to each other on the same line.*/
     white-space: nowrap; /* Prevent line breaks between elements white-space: nowrap;: This prevents line breaks between the form elements, ensuring that they stay on the same line.*/
     }
  </style>
     <div class="btn-group mt-2">
        <form action="{% url 'catalog:delete_all_filters' %}" method="post">
           {% csrf_token %}
           <button type="submit" class="btn btn-outline-dark flex-shrink-0 rounded-0">Smazat vše <i class="bi bi-dash-circle-fill"></i> </button>
        </form>
     </div>
    
     <form method="post" id="save_filters" action="{% url 'catalog:save_filters' %}">
           <button style="display: none;" type="submit">Apply Filter</button> 
           <!-- this is {{ sum_of }} invisible-->
           
        
        {% csrf_token %}
        <div class="btn-group mt-2">
           <button type="button" class="btn btn-outline-dark flex-shrink-0 rounded-0 dropdown-toggle thin-border" data-bs-toggle="dropdown" aria-expanded="false">Řadit</button>
           <ul class="dropdown-menu">
             
              {% for sort_by_price_value in filter_form.sort_by_price %}
              
              {% if sort_by_price_value == "created" %}
              
              {% else %}
              <li><a class="dropdown-item" id="sort_by_price"> {{ sort_by_price_value }}</a></li>
              {% endif %}
              {% endfor %}
           </ul>
        </div>
        <div class="btn-group mt-2">
           <button type="button" class="btn btn-outline-dark flex-shrink-0 rounded-0 dropdown-toggle thin-border" data-bs-toggle="dropdown" aria-expanded="false">Kategorie</button>
           <ul class="dropdown-menu">
             
              {% for category_value in filter_form.category_selection %}
              <li><a class="dropdown-item" id="category_value"> {{ category_value }}</a></li>
              {% endfor %}
           </ul>
        </div>
        <div class="btn-group mt-2">
           <button type="button" class="btn btn-outline-dark flex-shrink-0 rounded-0 dropdown-toggle thin-border" data-bs-toggle="dropdown" aria-expanded="false">Střih</button>
           <ul class="dropdown-menu">
              
              {% for cut_value in filter_form.cut_selection %}
              <li><a class="dropdown-item" id="cut_value"> {{ cut_value }}</a></li>
              {% endfor %}
           </ul>
        </div>
        <div class="btn-group mt-2">
           <button type="button" class="btn btn-outline-dark flex-shrink-0 rounded-0 dropdown-toggle thin-border" data-bs-toggle="dropdown" aria-expanded="false">Velikost</button>
           <ul class="dropdown-menu">
            
              {% for size_value in filter_form.size_selection %}
              <li><a class="dropdown-item" id="size_selection">{{ size_value }}</a></li>
              {% endfor %}
           </ul>
        </div>
     </form>
</div>
  <!-- start of other filter dropdowns as needed -->
<!-- labels start labels start -->
<div class="filters mb-5">
  <form action="{% url 'catalog:delete_selected_filter' %}" method="post">
      {% csrf_token %}

      <ul class="nav justify-content-center flex-sm-row">
          <!-- Sorting Label -->
          {% if selected_sorting == "-created" %}
          <li class="nav-item dropdown mt-2">
              <input type="hidden" name="selected_filter" value="Nejnovejsi">
          </li>
        {% elif selected_sorting and selected_sorting != "Nejnovejsi" %}
          <li class="nav-item dropdown mt-2">
              <input type="hidden" name="selected_filter" value="{{ selected_sorting }}">
              <button class="btn btn-light flex-shrink-0" id="selected_filter">
                  {{ selected_sorting }} <i class="bi bi-x"></i>
              </button>
          </li>
        {% endif %}
        
          
          <!-- Category Label -->
          {% if selected_category %}
              <li class="nav-item dropdown mt-2">
                  <input type="hidden" name="selected_filter" value="{{ selected_category }}">
                  <button class="btn btn-light flex-shrink-0 rounded-0"  id="selected_filter">
                      {{ selected_category }} <i class="bi bi-x"></i>
                  </button>
              </li>
          {% endif %}
          
          <!-- Cuts Label -->
          {% if selected_cuts %}
              <li class="nav-item dropdown mt-2">
                  <input type="hidden" name="selected_filter" value="{{ selected_cuts }}">
                  <button class="btn btn-light flex-shrink-0 rounded-0"  id="selected_filter">
                      {{ selected_cuts }} <i class="bi bi-x"></i>
                  </button>
              </li>
          {% endif %}
          
          <!-- Sizes Label -->
          {% if selected_sizes %}
              <li class="nav-item dropdown mt-2">
                  <input type="hidden" name="selected_filter" value="{{ selected_sizes }}">
                  <button class="btn btn-light flex-shrink-0 rounded-0" id="selected_filter">
                      {{ selected_sizes }} <i class="bi bi-x"></i>
                  </button>
              </li>
          {% endif %}
      </ul>
  </form>
</div>



  <div class="album py-2 bg-white">
    <div class="container justify-content-center align-items-center" style="min-height: 60vh;">
      {% if products %}
      <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3">

        
        {% for product in products %} 

        <!-- Single Product -->
        <div class="col-md-4 mb-4">
          <a href="{{ product.get_absolute_url }}">
            <div class="product-image-container">


          <div class="card mb-2 box-shadow">
            {% with first_photo=product.photos.first %}
            {% if first_photo %}
            <img class="card-img-top img-fluid" 
            data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" 
            alt="Thumbnail [100%x225]"
            src="{{ first_photo.photo.url }}"
            data-holder-rendered="true">
            {% endif %}


            {% if product.certificate.photo %}
            <img class="card-img-top img-fluid" 
            data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" 
            alt="{{ product.name }} certificate"
            src="{{ product.certificate.photo.url }}"
            data-holder-rendered="true">
           
            {% endif %}



            {% if product.discount %}
            <div class="discount-circle" style="background-color: #990000; font-size: 15px;"> -{{ product.discount }} % </div>

            {% elif product.new %}
            <div class="discount-circle"> NEW </div>
            {% elif product.limited %}
            <div class="discount-circle"> LIMITOVANÁ EDICE </div>
            {% elif product.skladem_na_miru %}
            <div class="discount-circle">SKLADEM<br>I&nbsp;NA MíRU </div>
            {% endif %}
          </div>
            {% endwith %}
            <div class="card-body d-flex flex-column" style="padding: 1rem;">
              <h5 class="fw-bolder"> {{ product.name }}</h5>
            
              <p class="card-text">{{ product.short_description }}</p>    
                          
            
             
                  {% if product.discount %}
                  <div><b class="fw-semibold"><del>{{ product.price }} Kč</del></div>
                    <div>{{ product.corrected_price }} Kč</div></b>
                  {% else %}
                  <b class="fw-semibold">{{ product.price }} Kč</b>
                  {% endif %}

                

            </div>
          </div>
        </a>
        </div>
      
       

        
        {% endfor %}
        
      </div>

    {% else %}
    <p></p>
      <p class="text-center">
          Zde nejsou žádné produkty. Prohlédněte si celou nabídku.
      </p>
  </div>
  
    {% endif %}
  </div>
  </div>
  </section>

<!-- End Best Sellers -->


  <!--
  <header class="masthead">
    <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
        <div class="d-flex justify-content-center">
            <div class="text-center">
            
                <h1 class="display-5 fw-bolder">{% trans "🪡 Spodní prádlo na míru" %}</h1>
                <h2 class="text-white mx-auto mt-2 mb-5">{% trans "Exkluzivní design 🤍" %}</h2>
                            
            </div> 
        </div> 
    </div>
</header>
-->




{% endblock %}

efir/catalog/templates/catalog/certificates.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load humanize %}
{% load i18n %}

{% block content %}
<!--Intro, Header Jumbotron --> 
<!-- link here: https://getbootstrap.com/docs/5.3/examples/jumbotron/ -->

<style>
  .dropdown-item.active {
  background-color: #000; /* Set background color to black */
  color: #fff; /* Set text color to white */
}
</style>

<!-- Catalog of Products -->
  <section class="jumbotron text-center">
    <div class="container">

        <h1 class="jumbotron-heading mt-5 mb-5">Dárkové certifikáty
        </h1>

          {% if not products %}
          
          
          <p></p>
          <p class="lead" style="text-center;">
              Aktuálně zde nejsou žádné produkty. Prohlédněte si celou nabídku v katalogu.</p>



          {% endif %}
       
      
    </div>


  

  <div class="album py-2 bg-white">
    <div class="container justify-content-center align-items-center" style="min-height: 20vh;">
      {% if products %}
      <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3">

        
        {% for product in products %} 


      
          <!-- Single Product -->
          <div class="col-md-4 mb-4">
            <a href="{{ product.get_absolute_url }}">
              <div class="product-image-container">


            <div class="card mb-2 box-shadow">
            
              {% if product.certificate.photo %}
            <img class="card-img-top img-fluid" 
            data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" 
            alt="{{ product.name }} certificate"
            src="{{ product.certificate.photo.url }}"
            data-holder-rendered="true">
           
            {% endif %}
              {% if product.discount %}
              <div class="discount-circle" style="background-color: #990000; font-size: 15px;"> -{{ product.discount }} % </div>
            
              {% else %}
             
              {% endif %}
            </div>
          
              <div class="card-body d-flex flex-column" style="padding: 1rem;">
                <h5 class="fw-bolder"> {{ product.name }}</h5>
              
                <p class="card-text">{{ product.short_description }}</p>                
                  
                {% if product.discount %}
                <div><b class="fw-semibold"><del>{{ product.price }} Kč</del></div>
                  <div>{{ product.corrected_price }} Kč</div></b>
                {% else %}
                <b class="fw-semibold">{{ product.price }} Kč</b>
                {% endif %}

              </div>
            </div>
          </a>
          </div>
        
        

    
        {% endfor %}
       
      </div>

    
    
  </div>
  
    {% endif %}
  </div>
  </div>
  </section>

<!-- End Best Sellers -->


  <!--
  <header class="masthead">
    <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
        <div class="d-flex justify-content-center">
            <div class="text-center">
            
                <h1 class="display-5 fw-bolder">{% trans "🪡 Spodní prádlo na míru" %}</h1>
                <h2 class="text-white mx-auto mt-2 mb-5">{% trans "Exkluzivní design 🤍" %}</h2>
                            
            </div> 
        </div> 
    </div>
</header>
-->




{% endblock %}

efir/catalog/templates/catalog/kontakty_success.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<div style="text-align: center;">
    <!-- About section-->
    <section class="py-5" id="about">
        <div class="container px-4 px-lg-5 my-5">
                    <h1 class="display-5 fw-bolder" style="text-align: center;">{% trans "Kontakty" %}</h1>
                    <p class="bi bi-envelope"><a href="mailto:zuzi@zuzikoko.com"> efirthebrand@gmail.com</a></p>
                <div style="text-align: center;">
                    <img src="{% static 'assets/img/intro_column_2.jpeg' %}" class="img-fluid" style="max-width: 100%;">
                </div>
                <br>
               <p>Váš dotaz byl odeslán.</p>
        </div>
    </section>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src='{% static "/js/scripts.js" %}'></script>
</div>
{% endblock %}

efir/catalog/templates/catalog/process.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load i18n %}
{% load humanize %}

{% block content %}
proces
{% endblock %}

efir/catalog/templates/catalog/set_discovery_completed.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load i18n %}
{% load humanize %}

{% block content %}
    
<style>
    .na_miru_container {
         max-width: 850px; /* Adjust the width as per your requirement */
         margin: 0 auto; /* Centers the content */
      }
</style>
    <div style="padding-bottom: 10%;">
        <div class="container px-5 px-lg-5 mt-5">
            <center>
            <h1> 
              Děkujeme za vyplnění dotazníku! 
            </h1>
            <br>
            <div class="na_miru_container">
            <p> 
              Během 2 pracovních dnů vám zašleme na váš e-mail individuální nabídku vašeho vysněného setu přesně podle informací, které jste poskytla. Těšíme se, že vám můžeme přinést právě ten správný kousek, který vás potěší!
            </p>
          </div>
                <br>
                
                <div><a href="{% url 'catalog:home' %}"><button class="btn btn-primary btn-md text-white m-1" style="background-color:  #000000; border-color: white;">Zpět do obchodu</button></a></div>
            
            </center>
        </div>
    </div>

{% endblock %}